db.url=jdbc:h2:mem:quantitydb;DB_CLOSE_DELAY=-1
db.username=sa
db.password=
db.pool.size=5
repository.type=database

logging.level.root=INFO
logging.level.com.app.quantitymeasurementapp=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n